


#SWITCH

---

#- name: SWITCH
  #hosts: switch
  #gather_facts: false
  #connection: local

  #tasks:
    #- include_tasks: dhcp.yml
    #- include_tasks: vlan.yml



#CUCM

- name: CUCM
  hosts: cucm
  gather_facts: false
  connection: local

  tasks:
    - include_tasks: analog.yml
    - include_tasks: phone.yml
    - include_tasks: video.yml
    - include_tasks: call.yml


#EDGE

- name: EDGE
  hosts: edge
  gather_facts: false
  connection: local

  tasks:
    - include_tasks: edge.yml



 #AUTO WIFI


- name: AUTO-WIFI
  hosts: wifi
  gather_facts: false
  connection: local

  tasks:
    - include_tasks: wifi.yml
